- name: Copy home config file
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ local_home }}/.{{item}}"
  vars:
    local_home: "{{ lookup('env', 'HOME') }}"
  with_items:
    - gitignore
    - irbrc
    - pdbrc
    - sqliterc

- name: Copy home config file with vars
  template:
    src: "{{ role_path }}/templates/{{ item }}"
    dest: "{{ local_home }}/.{{item}}"
  vars:
    local_home: "{{ lookup('env', 'HOME') }}"
  with_items:
    - gitconfig
    - pypirc
